//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class kwe_Tasks
    {
        public int IdTask { get; set; }
        public int IdCategory { get; set; }
        public string CategoryName { get; set; }
        public string TaskName { get; set; }
        public int IdWorkers { get; set; }
        public string LoginStoart { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string StatusName { get; set; }
        public int IdTaskStatus { get; set; }
        public string PriorityName { get; set; }
        public int IdTaskPriority { get; set; }
    }
}
