//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CheckListsEntities : DbContext
    {
        public CheckListsEntities()
            : base("name=CheckListsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_TaskCategories> tbl_TaskCategories { get; set; }
        public virtual DbSet<tbl_TaskPriority> tbl_TaskPriority { get; set; }
        public virtual DbSet<tbl_Tasks> tbl_Tasks { get; set; }
        public virtual DbSet<tbl_TaskStatus> tbl_TaskStatus { get; set; }
        public virtual DbSet<tbl_Workers> tbl_Workers { get; set; }
        public virtual DbSet<kwe_Tasks> kwe_Tasks { get; set; }
    }
}
